server:
  port: 8086
  session-timeout: 36000
  tomcat:
    uri-encoding: utf-8
    # max-threads: 1000
    # min-spare-threads: 30
security:
  basic:
    enabled: false
spring:
  activiti:
    database-schema-update: true
    check-process-definitions: false
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: me.zbl.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.mybatis: DEBUG
    me.zbl: DEBUG # 设置你自己的包名日志级别为 DEBUG
